general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# Lock the screen after 5min of inactivity.
listener {
    timeout = 300  # 5min
    on-timeout = loginctl lock-session
}

# Turn off the screen after 5.5min of inactivity, and turn it on again when activity is detected.
listener {
    timeout = 330  # 5.5min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# For manual lock - Turn off the screen 30s after locking (checks if hyprlock is running).
listener {
    timeout = 30
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = pidof hyprlock && hyprctl dispatch dpms on
}
